### ISSUE TITLE
`TimestampSigner.validate` will raise `SignatureExpired`

### ISSUE THREAD

**Issue by mattbasta** [pallets/itsdangerous#11]
I'm not 100% sure of the intended functionality, but it seems like `TimestampSigner.validate` should not raise any exceptions. If the timestamp is older than the max age, the function should return `False` rather than raise an exception.

**Comment by arnuschky** [comment]
Well, it might be desirable to differentiate between expired signatures and completely invalid ones. Technically, a signature can't be invalidated by time, either it's valid or it's not. The timestamp is additional payload that is evaluated after the signature proved to be valid.

Note that `TimestampSigner.validate` also raised `BadTimeSignature` which isn't caught either.

I would close this.

**Comment by davidism** [comment]
`SignatureExpired` subclasses `BadTimeSignature` which subclasses `BadSignature`, so they will all be caught and return `False` from `validate`.

~~~python
s = TimestampSigner('secret')
s.validate(s.sign('hello'), max_age=-1)  # force expired signature
# returns False
~~~
