### ISSUE TITLE
1.0.0 Removed

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/itsdangerous#112]
I’m sorry for the inconvenience caused but I missed that there was a signature change that made it into 1.0. I yanked the release now because this change had some cery bad consequences and yanking the release is less risky in comparison.

If someone already uses 1.0 roll back to 0.24 and set the hash algoritm to sha 512 if needed. Note though that it will be unlikely we switch to that algorithm going forward.

I will figure out a way forward over the weekend.

For more information see #111

**Comment by alexbecker** [comment]
Please do not yank already-released packages. Lots of tooling assumes that PyPI releases will never vanish, and when they do it causes nasty problems. I agree the change in default hash algorithm was unfortunate, but 1.0 *is* a major release and some of your users (my company, for one) have already upgraded and handled the change.

**Comment by mitsuhiko** [comment]
@alexbecker i understand it's unfortunate but pypi does not provide with a way to just hide a release. The issue is that even though you already handled the change, the change will be rolled back in future releases as well so that does not help you much. For all intends and purposes 0.24 with changes is what 1.x will become.

**Comment by alexbecker** [comment]
A less disruptive way to handle this would have been to immediately re-release 0.24 as 1.0.1, with a changelog explaining why.

**Comment by prometheanfire** [comment]
Yep, broke openstack ci too.  http://logs.openstack.org/52/612252/8/check/requirements-tox-py27-check-uc/138a9ea/job-output.txt.gz#_2018-10-26_18_58_15_139922

I do agree that the proper way of handling it would be to release it as 1.0.1.  If the change is rolled back in a future release then you release that as 2.0.0  semantic versioning exists for a reason.

**Comment by davidism** [comment]
@bsdanders if your builds are failing because of package capitalization, you need to fix your build tool. PyPI and pip both normalize names to lowercase with underscores. The names will change to be consistently capitalized.

Please keep the discussion on topic for this issue.

**Comment by mitsuhiko** [comment]
@bsanders I understand the frustration. I'm sorry :(

**Comment by davidism** [comment]
1.1.0 has been released. It reverts to SHA-1, and adds a fallback mechanism to safely upgrade signing parameters in the future. It also reverts the package name to all lowercase "itsdangerous".

You can read a longer explanation here: https://palletsprojects.com/blog/itsdangerous-1-1-0-released/

**Comment by Gnouc** [comment]
@mitsuhiko @davidism my flask app using itsdangerous session interface stop working after upgrading to 1.1.0.

Revert to 0.24 works.

**Comment by davidism** [comment]
@Gnouc that's not enough information to go on. `ItsDangerousSessionInterface` is not part of Flask, it must be from some other code. `SessionInterface` does not have a `get_serializer` method. All Flask's tests still pass with itsdangerous 1.1.0. Also, the built-in session interface already uses `key_derivation = 'hmac'`, which appears to be the only change in your code. You'll need to open a new ticket with the appropriate ammount of information demonstrating the issue.

**Comment by davidism** [comment]
Locking this because the issue is resolved. If you have a new issue, please open a new ticket.
