### ISSUE TITLE
Timestamp singer get_timestamp implementation differs between 0.24 and 1.x

### ISSUE THREAD

**Issue by ergo** [pallets/itsdangerous#118]
Hi,

It seems that services using itsdangerous 0.24 can't communicate with 1.1.0 and timestamp singer fails with too old timestamp error.

0.24 has:

    def get_timestamp(self):
        """Returns the current timestamp.  This implementation returns the
        seconds since 1/1/2011.  The function must return an integer.
        """
        return int(time.time() - EPOCH)

But 1.1 has:

    def get_timestamp(self):
        """Returns the current timestamp. The function must return an
        integer.
        """
        return int(time.time())

In its implementation.

**Comment by ThiefMaster** [comment]
See #46 - this is intentional (and 1.0 was a major version bump so breaking changes are acceptable there)

**Comment by ergo** [comment]
@ThiefMaster then https://github.com/pallets/itsdangerous/issues/111 change was acceptable too by same logic.
