### ISSUE TITLE
1.0.0 missing from pypi

### ISSUE THREAD

**Issue by Marviel** [pallets/itsdangerous#119]
We use Pipenv to manage our dependencies, and during our recent builds, we were unable to access version 1.0.0 as it does not appear to be on pypi any longer.

This is pretty inconvenient, as we are trying to lock our dependencies for predictable behavior.

This seems to coincide with the 1.1.0 release that occurred 4 days ago, if that helps.

Some answers on this would be most appreciated. Thanks!

**Comment by ThiefMaster** [comment]
See #112 and #111
