### ISSUE TITLE
Cannot import name 'SigningAlgorithm'

### ISSUE THREAD

**Issue by Algruun** [pallets/itsdangerous#121]
`ImportError: cannot import name 'SigningAlgorithm' from 'itsdangerous' (/Users/algruun/environment/bitshares/trusty/venv/lib/python3.7/site-packages/itsdangerous/__init__.py)`
Just wanted to use this part, but it raising this exception

**Comment by davidism** [comment]
This is on purpose, see the 1.0 changelog. Import it from its full location: `from itsdangerous.signing import SigningAlgorithm`.

> Refactor code from a single module to a package. Any object in the API docs is still importable from the top-level itsdangerous name, but other imports will need to be changed. A future release will remove many of these compatibility imports. (#107)
