### ISSUE TITLE
Support for newer hashlib digest e.g. blake2

### ISSUE THREAD

**Issue by jwag956** [pallets/itsdangerous#134]
Newer versions of Py3 support a hashlib.blake2
Its constructor takes a variety of parameters.
From my reading of code - there is no way to send into Signer parameters/kwargs to be used as part of signer digest initialization.

**Comment by davidism** [comment]
Fairly sure there are arguments to override that, if not please add an example of what you need. However, there's no real point, even md5 is still secure as it's used in HMAC, there's not really a benefit to using more complex hashes.

**Comment by jwag956** [comment]
itsdangerous 1.1. Look at HMACAlgorithm() - it just takes a digest_method argument. Each time you ask for a signature - it creates a new HMAC - and all it passes is digest_method. that didn't matter before since all hashlib digests didn't actually take any initialization parameters. Blake2 does.

As for not needing this - unless I am mistaken - the current state of itsdangerous ships with a known-to-be-broken hash (sha1) as the default. 1.0.0 attempted to up that to SHA512 but had to back that out.
HMAC (as in the python class) isn't responsible for any hashing - that is delegated to the digest_method. 

Since for example flask-security uses itsdangerous for signing authentication tokens - seems like supporting latest hashes as published in python std library would be useful.
Note that you CAN use blake2 since it has initialization defaults - you just can't customize it.

So I would consider this a low to medium enhancement request - and I think would be pretty easy.

**Comment by davidism** [comment]
SHA1 is not broken in HMAC. MD5 is still secure in HMAC. The hash is not used directly, the security model of HMAC is completely different.

The change was made to appease people who saw "SHA1" and thought itsdangerous was insecure. It wasn't actually required and was backed out for compatibility reasons. Again, the entire itsdangerous API can be subclassed, that's a valid way to customize it for special requirements.

**Comment by jwag956** [comment]
Thanks - more research says you are basically right - people are recommending 'walk..not run' from HMAC-SHA1 - no need for advanced hashing as long as using HMAC...
