### ISSUE TITLE
JWT Serializer body can be decoded without any secret key needed

### ISSUE THREAD

**Issue by Alonreznik** [pallets/itsdangerous#135]
Hi there.
As it seems from my tests, the TimedJSONWebSignatureSerializer provides token of headers and body which is just can be decoded using base64_decode function. No checking of secret key in the serializer. Therefore, the token is just exposed by anyone that knows how to split the token with `.` seperator, and with base64 decoder.

For example:

```
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import base64_decode


s = Serializer(secret_key='MyNameIsSecret')
token = s.dumps({"token_id": {"my": "name"}})
print(token)

header, body, something_else = token.split(b'.')

print(base64_decode(body))
```

Result:

```
eyJhbGciOiJIUzI1NiIsImV4cCI6MTU2MTI0MTczOCwiaWF0IjoxNTYxMjM4MTM4fQ.eyJ0b2tlbl9pZCI6eyJteSI6Im5hbWUifX0.hYY7ILk727DWUKU8TnYuRv2PCy3-1dxvHLS0LLTTmWg
{"token_id":{"my":"name"}}
```

In that case - what is the use of the secret key in this JWTSerializer, if there is no real encryption of the data?

Thanks

**Comment by ThiefMaster** [comment]
The whole point of itsdangerous is signing, not encryption. Like this you can transmit (non-secret) data through untrusted channels, e.g. session cookies stored in the browser.
