### ISSUE TITLE
Static analysis?

### ISSUE THREAD

**Issue by huornlmj** [pallets/itsdangerous#136]
Are there plans to introduce static analysis of this code?

**Comment by ThiefMaster** [comment]
What kind of static analysis?

**Comment by huornlmj** [comment]
Sonarcube / Checkmarx etc. or even Pylint.  Scan.coverity.com offers public Github SA integration for C/C++/Java.  I don't think it covers Python though.

**Comment by davidism** [comment]
We use black, flake8, reorder-python-import, and pre-commit. I do not see the need for other tools at this time.

https://github.com/pallets/itsdangerous/blob/ea267c1d3b16cf1fffd3c21d0ea174fc8bcbe73c/setup.cfg#L22-L36

https://github.com/pallets/itsdangerous/blob/ea267c1d3b16cf1fffd3c21d0ea174fc8bcbe73c/.pre-commit-config.yaml#L2-L18
