### ISSUE TITLE
Session expiration isn't signed

### ISSUE THREAD

**Issue by taleinat** [pallets/itsdangerous#139]
The expiration date+time is written to a section of the cookie that isn't signed. This makes it simple to use old session cookies to access systems.

**Comment by ThiefMaster** [comment]
The code says something else:

https://github.com/pallets/itsdangerous/blob/c96e82d42ed46b889321989569d40ce7b205bded/src/itsdangerous/timed.py#L41-L42

**Comment by taleinat** [comment]
Ah, my bad! Thanks for the clarification, @ThiefMaster.
