### ISSUE TITLE
Public key algorithms?

### ISSUE THREAD

**Issue by Riamse** [pallets/itsdangerous#140]
It doesn't seem possible for an observer to validate a signed message, only the signer can do that.

One cool feature of public-key cryptography is that Alice can sign a message using her private key, and people like you or me can verify that the message is in fact from Alice by using her public key.

Are we able to implement public-key functionalities so we can use public-key algorithms like DSA?

(A side effect of using something like DSA is that every time you sign something, you get a different signature, which may or may not be a problem. I can think of ways around that but I don't know if they compromise its security.)

**Comment by davidism** [comment]
That's not the purpose of the default configuration of this library, although I'm sure you could build a signer that uses DSA instead.
