### ISSUE TITLE
Use json instead of simplejson

### ISSUE THREAD

**Issue by ijl** [pallets/itsdangerous#146]
itsdangerous and by extension flask, starlette, and others use simplejson if it's installed due to:

```python
try:
    import simplejson as json
except ImportError:
    import json
```

Is there still a reason to use simplejson? I don't know of a feature or compatibility reason.

The reason I have seen mentioned is better performance. That is not the case with at least python3.6+ and a modern distribution (that probably compiled python with PGO and LTO) with simplejson compiled. See [these benchmarks](https://github.com/ijl/orjson#performance).

If simplejson is installed in a container without a compiler, it falls back to running in pure Python. This is a footgun:

```python
In [1]: import json, simplejson

In [2]: data = list(range(0, 100000))

In [3]: %timeit json.dumps(data)
17.4 ms ± 1.14 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]: %timeit simplejson.dumps(data)
89.4 ms ± 7.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

It seems preferable to just use json.

**Comment by CoburnJoe** [comment]
``json`` was added to Python 2.6, so the main reason to use ``simplejson`` is backwards compatibility with Python 2.4+ (although, as someone who occasionally has to maintain Python 2.4 code, the sooner it dies the better).

Considering the oldest test suite on this project runs on Python 2.7, it seems a good candidate to refactor this.

**Comment by davidism** [comment]
Yeah, I'm fairly ok with this once we drop Python 2.

**Comment by dankarpinski** [comment]
When using the `2.0.0a1` build my tests failed and I've narrowed it down to this change.

One big difference between `json` and `simplejson` is that the latter supports serializing `Decimal` types. Flask-sqlalchemy uses `Decimal`, so this change might affect quite a few people when they upgrade.
