### ISSUE TITLE
Add encrypted storage

### ISSUE THREAD

**Issue by dwt** [pallets/itsdangerous#224]
I would really like to have the option to transport encrypted secrets from one server to another through cookies. I am currently implementing this to transfer user information encrypted between a normal pyramid based server who does the login and an asynchronous game server who consumes it. I'm currently implementing this using https://github.com/google/keyczar - which is deprecated and not ported to python3 - but a joy to use.

So, what do you think? I think the option to encrypt cookies with its dangerous would be highly nice.

**Comment by davidism** [comment]
This is out of scope.
