### ISSUE TITLE
Work with Flask 1.1.2 and upgrade itsdangerous to 2.0.0 won't parse bytes

### ISSUE THREAD

**Issue by ranmx** [pallets/itsdangerous#238]
Hi,

I work with Flask 1.1.2 and upgrade itsdangerous from 1.1.0 to 2.0.0, find it won't be able to parse bytes.

```
from flask import jsonify, Flask

def test():
    app = Flask(__name__)
    with app.app_context():
        a = {'1': b'abcd'}
        print(jsonify(a))

test()
```

with ItsDangerous 1.1.0 this code works but with 2.0.0 it comes out
```
".../python3.7/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File ".../python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File ".../python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File ".../python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ".../python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File ".../python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File ".../python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

Environment:

- Python version: 3.7.2/3.7.10 tested
- Flask version: 1.1.2
- ItsDangerous version: 1.1.0 to 2.0.0

**Comment by neuroid** [comment]
I'm guessing that this stopped working for you because itsdangerous no longer depends on simplejson. Try installing simplejson explicitly. See also https://github.com/pallets/flask/issues/3555 for a similar change in Flask 2.0.0.

**Comment by davidism** [comment]
In addition to the suggestions above, be sure to use a tool like [pip-compile](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you upgrade.
