### ISSUE TITLE
base64encode should be injected as a dependency in Signer class

### ISSUE THREAD

**Issue by vianney-g** [pallets/itsdangerous#249]
Usage of base64.urlsafe_b64encode is hard coded in Signer class.

Changing encoder can be resolve by subclassing Signer class such as:

```python
class _Signer(Signer):
    """Change alt char in encoding
    """

    def get_signature(self, value: Union[str, bytes]) -> bytes:
        value = want_bytes(value)
        key = self.derive_key()
        sig = self.algorithm.get_signature(key, value)
        sig_string = want_bytes(sig)
        return b64encode(sig_string, altchars=b"&$").rstrip(b"=")

```

It's a lot of work (sure I over estimate my time of work :smile: ) for something that could (and should) easily be made with DI. Encoder should be given as a param of Signer class.

**Comment by davidism** [comment]
Thanks for the suggestion. However, we want to stick with the subclass pattern.
