### ISSUE TITLE
Version 2.1.0 cannot import name 'json' from 'itsdangerous'

### ISSUE THREAD

**Issue by Donovant** [pallets/itsdangerous#289]
When trying to use Flask, which pulls Version 2.1.0, we're seeing the following error:

  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/site-packages/itsdangerous/__init__.py)

The program should correctly import the json library if its needed (which I believe it is) or it should be removed.

Environment:

- Python version: 3.8
- ItsDangerous version: 2.1.0
- Flask version: 1.0.2

**Comment by davidism** [comment]
Flask 1.x has not been supported for quite some time. Upgrade flask, and pin your dependencies with something like pip-tools.

**Comment by LeanderLW** [comment]
I got the same problem.
ImportError while loading conftest '/home/jenkins/workspace/SASE-ZTNA/Build/BuildControllerService/controller-connectorsvc/controller-connectorsvc/test/conftest.py'.
conftest.py:3: in <module>
    from src.create import create_app
../src/create.py:14: in <module>
    from flask import Flask
testenv/lib/python3.7/site-packages/flask/__init__.py:19: in <module>
    from . import json
testenv/lib/python3.7/site-packages/flask/json/__init__.py:15: in <module>
    from itsdangerous import json as _json
E   ImportError: cannot import name 'json' from 'itsdangerous' (/home/jenkins/workspace/SASE-ZTNA/Build/BuildControllerService/controller-connectorsvc/controller-connectorsvc/test/testenv/lib/python3.7/site-packages/itsdangerous/__init__.py)

**Comment by shaktis** [comment]
@davidism it would help if the `flask` maintainers could pin their versions -- see https://github.com/pallets/flask/blob/main/setup.py#L9  -- may be you can ask them?
