### ISSUE TITLE
Include the __version__ inside the itsdangerous.py file

### ISSUE THREAD

**Issue by lipis** [pallets/itsdangerous#30]
Usually that's the only file that is being used and it's nice to know which version is there

**Comment by cclauss** [comment]
Something like line 13 of the [Flask __init__.py file](https://github.com/pallets/flask/blob/master/flask/__init__.py)

Or like the last line of the [Click __init__.py file](https://github.com/pallets/click/blob/master/click/__init__.py)

Or like line 30 of the [Jinja __init__.py file](https://github.com/pallets/jinja/blob/master/jinja2/__init__.py)

Or like line 17 of the [markupsafe __init__.py file](https://github.com/pallets/markupsafe/blob/master/markupsafe/__init__.py)

Or like line 23 of the [Werkzeug __init__.py file])https://github.com/pallets/werkzeug/blob/master/werkzeug/__init__.py)

**Comment by lipis** [comment]
Yes please :)

**Comment by untitaker** [comment]
Will merge a PR that changes this and simultaneously changes setup.py to read the version from __init__.py just like all the other projects.

Just don't forget to mention me so I get notified.

**Comment by davidism** [comment]
a8b386aa74c751b56af6749fd0f9f2349ab23953

**Comment by lipis** [comment]
Awesome! and now you will have to make a release..
