### ISSUE TITLE
Last character of serialized/signed data not robust

### ISSUE THREAD

**Issue by ertand** [pallets/itsdangerous#368]
It is possible to modify the last character of a serialized string without provoking a decoding error.
Maybe not a bug but I find it strange.

Effective on several examples, including those given in the documentation of itsDangerous :

### Example 1
from itsdangerous.serializer import Serializer
`s = Serializer("secret-key")`
`s.dumps([1, 2, 3, 4])`
_b'[1, 2, 3, 4].r7R9RhGgDPvvWl3iNzLuIIfELmo_

`s.loads('[1, 2, 3, 4].r7R9RhGgDPvvWl3iNzLuIIfELmo')`
_[1, 2, 3, 4]_

**The last letter ('o') can be replaced by p, q or r :**

`s.loads('[1, 2, 3, 4].r7R9RhGgDPvvWl3iNzLuIIfELmp')`
_[1, 2, 3, 4]_

`s.loads('[1, 2, 3, 4].r7R9RhGgDPvvWl3iNzLuIIfELmq')`
_[1, 2, 3, 4]_

`s.loads('[1, 2, 3, 4].r7R9RhGgDPvvWl3iNzLuIIfELmr')`
_[1, 2, 3, 4]_

But replacing by 's' fails :
`s.loads('[1, 2, 3, 4].r7R9RhGgDPvvWl3iNzLuIIfELms')`
BadSignature: Signature b'r7R9RhGgDPvvWl3iNzLuIIfELms' does not match

### Example 2
`from itsdangerous import Signer`
`s = Signer("secret-key")`
`s.sign("my string")`
_b'my string.wh6tMHxLgJqB6oY1uT73iMlyrOA'_

`s.unsign(b"my string.wh6tMHxLgJqB6oY1uT73iMlyrOA")`
_b'my string'_

`s.unsign(b"my string.wh6tMHxLgJqB6oY1uT73iMlyrOB")`
_b'my string'_

`s.unsign(b"my string.wh6tMHxLgJqB6oY1uT73iMlyrOC")`
_b'my string'_

`s.unsign(b"my string.wh6tMHxLgJqB6oY1uT73iMlyrOD")`
_b'my string'_

`s.unsign(b"my string.wh6tMHxLgJqB6oY1uT73iMlyrOE")`
_BadSignature: Signature b'wh6tMHxLgJqB6oY1uT73iMlyrOE' does not match_

## Expected behavior:
I would have expected a _BadSignature_ exception for any signature not exactly equal to the original one

## Environment:
- Python version: 3.11.8
- ItsDangerous version: 2.1.2

**Comment by davidism** [comment]
Signatures are not actually ASCII characters, they're base64 encoded bytes. This results in some trailing bytes/bits being "padding" to a standard length/boundary. This isn't a property of itsdangerous, but of base64.

If you believe you've found a security issue then first you should report it privately, but second you need to demonstrate being able to change the _data_ without changing the signature.
