### ISSUE TITLE
Support digest_size when using blake2s or blake2b

### ISSUE THREAD

**Issue by awiprayitno** [pallets/itsdangerous#386]
Hi, currently I cannot find a way to set the digest_size when using blake2s or blake2b.

Can someone point me in the direction of maybe subclassing the HMACAlgorithm? Thanks

**Comment by davidism** [comment]
You would implement a custom `SigningAlgorithm` then pass it to the signer.

https://github.com/pallets/itsdangerous/blob/6567d656f0386cfe647c9ad5cdfc59e68150487c/src/itsdangerous/signer.py#L15-L28

https://github.com/pallets/itsdangerous/blob/6567d656f0386cfe647c9ad5cdfc59e68150487c/src/itsdangerous/signer.py#L136
