### ISSUE TITLE
add expiry date to TimestampSigner

### ISSUE THREAD

**Issue by wrow** [pallets/itsdangerous#40]
Could you please add some kind of expiry date to the TimestampSigner? I want to allow my users to decide how long their links should be valid. Currently i have to include the current timestamp (by using the TimestampSigner) and the max age the user wants. So in such a case it would be much more helpful to handle the integrated Timestamp as expiry date and not as creation date ... but even if i would handle the date check myself, it seems not to be possible to define the now-timestamp used by the TimestampSigner.

**Comment by davidism** [comment]
This is a good case for writing your own Serializer subclass.
