### ISSUE TITLE
otr addon

### ISSUE THREAD

**Issue by engellove** [pallets/itsdangerous#42]
der tv planer geht nich der rest geht

**Comment by arnuschky** [comment]
Ich glaube du hast hier auf's falsche Repo kommentiert... Was hattest du vor?

**Comment by engellove** [comment]
es geht um otr addon

2015-05-29 9:57 GMT+02:00 arnuschky <notifications@github.com>:

**Comment by arnuschky** [comment]
Ja, was wohl ein Addon zu XMBC ist, oder? Was hat das ganze mit einer Library für's signieren von Daten zu tun?

Generell wäre ein bisschen mehr Info hilfreich. Was geht nicht, was versuchst du zu tun, was verwendest du für Versionen etc.

**Comment by engellove** [comment]
Das addon ist ein xmbc addon und es geht der tv planner nicht .ausserdem
auch das löschen der alten dateien nicht.

Am 30. Mai 2015 um 11:33 schrieb arnuschky <notifications@github.com>:

**Comment by arnuschky** [comment]
Schon klar. Aber das Projekt auf dem du hier kommentierst hat *nix* damit zu tun! :)
Es geht hier um eine Softwarebilbiothek die nichts mit XMBC zu tun hat.

Ich glaube du willst hierhin: https://github.com/wrow/xbmc-otr
