### ISSUE TITLE
Is there a way to know how much time remains before a token expires?

### ISSUE THREAD

**Issue by tonyennis** [pallets/itsdangerous#43]
Just what the subject says.

**Comment by tonyennis** [comment]
I did try make_headers() but this seems to make the created-at and expired-at values anew.

**Comment by Kijewski** [comment]
Have a look at the code between the lines [421](https://github.com/mitsuhiko/itsdangerous/blob/master/itsdangerous.py#L421) and [458](https://github.com/mitsuhiko/itsdangerous/blob/master/itsdangerous.py#L458).

**Comment by tonyennis** [comment]
Right. I have been there. I was hoping there was already a facility to return it. Yes, if there were such a method, the code would have been refactored. But it does not hurt to ask...

**Comment by saiparty** [comment]
if you are using TimedJSONWebSignatureSerializer to generate the tokens, u can set return_header to True while you are loading a token, the returned header has values through which you can compute the remaining time.

**Comment by davidism** [comment]
~~~python
max_age = 300
serializer = TimedSerializer('secret')
token = s.dumps('message')
_, ts = t.loads(t, max_age=max_age, return_timestamp=True)
remaining = max_age - (datetime.utcnow() - ts).total_seconds()
~~~
