### ISSUE TITLE
OS Dates before 01/01/2011 are broken

### ISSUE THREAD

**Issue by elementalistic** [pallets/itsdangerous#46]
I'm using an embedded linux with a startup kernal time of 01/01/2010, with flask hosted site as a config tool.  If the device doesn't have an internet connection (to update time from NTP), and they trigger TimeStampSigner.sign() function in itsdangerous.py, the int_to_byte assert fails as num is < 0.

I've not delved into why the logic expects the date to be greater then 2011, but it breaks it for me.

**Comment by egorf** [comment]
Hi!
I have the same problem. I am using a flask app in an embedded Linux IOT device. Default startup time is 01.01.2000. Do you guys plan to fix this? The only workaround I found is setting date on startup every time. 
Another question is why is it exactly 2011?
Thank you!
