### ISSUE TITLE
Upload a wheel distribution to PyPi

### ISSUE THREAD

**Issue by orf** [pallets/itsdangerous#47]
As per http://pythonwheels.com/, itsdangerous doesn't seem to have a wheel distribution on PyPi. Any chance this could be added?

**Comment by Ofekmeister** [comment]
Should this be closed?

**Comment by davidism** [comment]
Not until a wheel is actually uploaded.

**Comment by Ofekmeister** [comment]
Ah, I see. I didn't realize there has been such a long time since the last release.

**Comment by davidism** [comment]
This will be resolved in the next release.
