### ISSUE TITLE
Only Chinese version on itsdangerous.readthedocs.org?

### ISSUE THREAD

**Issue by dakra** [pallets/itsdangerous#48]
When you go to http://itsdangerous.readthedocs.org/ (3rd link on google, and many people click it first because they know readthedocs is the nice formatted documentation) it redirects to
http://itsdangerous.readthedocs.org/zh_CN/latest/ and it seems there is not even a different version up there.
I think it should be english by default.

**Comment by davidism** [comment]
Anyone can claim names on rtd.  The official docs are at https://pythonhosted.org/itsdangerous/.

**Comment by dakra** [comment]
Thing was that it's not something else on rtd but the Chinese doc for this module and it shows up on the first Google page so I thought it was under your control and you should fix it since many people click rtd links first for python documentation. 
Nevermind then :)
