### ISSUE TITLE
RFC7519 compliance

### ISSUE THREAD

**Issue by Metalgrid** [pallets/itsdangerous#51]
According to [RFC7519](https://tools.ietf.org/html/rfc7519), the expiration date should be in the claims, rather than the header. Would this be supported?

**Comment by davidism** [comment]
itsdangerous implements JWS with some extra headers, it does not implement JWT.  For JWT, payload would be required to be a JSON object, where we allow any JSON serializable value.

I'd consider a pull request that added a `JSONWebTokenSerializer` building on the `JSONWebSignatureSerializer`.
