### ISSUE TITLE
itsdangerous throws BadSignatureException when using URLSafeSerializer with '_' separator

### ISSUE THREAD

**Issue by tjerkw** [pallets/itsdangerous#55]
This code fails: 

    def test(count=1030):
        import itsdangerous
        secret = 'test'
        s = itsdangerous.URLSafeSerializer(secret, signer_kwargs={'sep': '_'})
        for i in xrange(count):
            val = gen_random_string(len=3)
            s.loads(s.dumps(val))

Improvment: let itsdangerous throw an exception if an invalid seperator is used.

**Comment by tjerkw** [comment]
I also tought the string has BASE64 + sep + BASE64, but apparently thats not the case.

**Comment by davidism** [comment]
I can't reproduce this issue.  `_` (and any character not used by base64) is a valid separator. I think it's reasonable to assume the user isn't picking a character that will be used by the encoding.
