### ISSUE TITLE
JES support

### ISSUE THREAD

**Issue by m000** [pallets/itsdangerous#59]
Would it make sense to also support JES (JSON Encryption Standard) in addition to JWS? This would allow you to store potentially sensitive information in untrusted storage.

E.g. think of a registration form which includes a lot of personal information. Traditionally, the form information are stored locally on the server and a verification link is sent to an email. This puts the burden of temporary storage on the server.
If JES is supported, the submitted form data could be included in the verification link. Since email is considered insecure, we don't want this information to be retrievable by anyone else but the server. The benefit in doing so is that the server doesn't have to handle (store and purge) unverified information.

Of course this could be implemented with ad-hoc serialization, but since there's a standard for it, maybe it's better to support it.

**Comment by davidism** [comment]
I think this is beyond the scope of itsdangerous, although there shouldn't be anything preventing implementing this as a `Serializer` subclass.  I'd consider a pull request that added `JSONWebEncryptionSerializer` similar to `JSONWebSignatureSerializer`, if someone can invest the time.  Consider using the [cryptography](https://cryptography.io) package.
