### ISSUE TITLE
Support for other hashing functions?

### ISSUE THREAD

**Issue by TheChuckster** [pallets/itsdangerous#66]
Is this on the roadmap? I'm concerned about the security of SHA1 against GPU attacks.

**Comment by davidism** [comment]
Could you describe your concern with SHA1 as it is used in this library in more detail?

Attacks against hash functions are not representative of their security as part of message authentication.  https://en.wikipedia.org/wiki/Hash-based_message_authentication_code#Security

You can subclass or assign to override [`default_digest_method`](https://pythonhosted.org/itsdangerous/#itsdangerous.Signer.default_digest_method) if this is a concern for you.

**Comment by davidism** [comment]
See #80, I'm upgrading this to SHA-512 after more discussion.
