### ISSUE TITLE
Dictionary payload with numeric keys become strings

### ISSUE THREAD

**Issue by baubie** [pallets/itsdangerous#67]
Happens using Serializer and URLSafeSerializer:

```
>>> s.loads(s.dumps({1: 2}))
{'1': 2}
```

I don't think this should be intended behaviour -- using version 0.24 with Python 3.5.

**Comment by ThiefMaster** [comment]
Cannot be avoided when using a json serializer. JSON keys are always strings...

**Comment by davidism** [comment]
You can use a different internal serializer, such as custom JSON that converts a dict to a list of key, value pairs, or YAML.  Pass `serializer=` when instantiating the serializer (confusingly named, yes).  https://pythonhosted.org/itsdangerous/#itsdangerous.Serializer  This isn't something that will be changed in the library though.
