### ISSUE TITLE
Serializer.load_payload overrides in subclasses have incompatible signatures

### ISSUE THREAD

**Issue by ambv** [pallets/itsdangerous#74]
[Mypy](https://github.com/python/mypy) recently introduced stricter checks for function signature compatibility (https://github.com/python/mypy/pull/2521). Since `itsdangerous` is included in the typeshed library with typing stubs, it found an issue with the signatures of `load_payload`. Consider:
```py3
class Serializer:
  def load_payload(self, payload, serializer=None): ...
```
vs.
```py3
class JSONWebSignatureSerializer(Serializer):
  def load_payload(self, payload, return_header=False): ...
```
vs.
```py3
class URLSafeSerializerMixin(object):
  def load_payload(self, payload): ...

class URLSafeSerializer(URLSafeSerializerMixin, Serializer): ...
class TimedSerializer(Serializer): ...
class URLSafeTimedSerializer(URLSafeSerializerMixin, TimedSerializer): ...
```

Basically, it's invalid to replace `load_payload()` accepting an optional kwarg with an implementation that doesn't.

**Comment by davidism** [comment]
PyCharm has complained about it for a while too. If you have a fix in mind, a patch would be great, otherwise I'll investigate.

**Comment by ambv** [comment]
Alright, PR ready.
