### ISSUE TITLE
Low precision of timestamp while creating a token

### ISSUE THREAD

**Issue by paulgoetze** [pallets/itsdangerous#76]
It looks like the timestamp that is used for tokengeneration is not precise enough. It seems like it only uses an accuracy on a second level but is not handling milliseconds?

You can reproduce this with the following snippet: 

```python
import time
from itsdangerous import URLSafeTimedSerializer

serializer = URLSafeTimedSerializer('some-secret', 'some-salt')

for i in range(1, 10):
    print(serializer.dumps({'test': 1}))
    time.sleep(0.5)
```

which gives me the same token twice within 1 second: 

```
eyJ0ZXN0IjoxfQ.C48Cmw.oaO_dsjdedzISztrO9Vg9HbEsYs
eyJ0ZXN0IjoxfQ.C48Cmw.oaO_dsjdedzISztrO9Vg9HbEsYs
eyJ0ZXN0IjoxfQ.C48CnA.D_jhOJP5Pjw5ZL63RJ85Od8Ol5U
eyJ0ZXN0IjoxfQ.C48CnA.D_jhOJP5Pjw5ZL63RJ85Od8Ol5U
eyJ0ZXN0IjoxfQ.C48CnQ.O9K1VLYhxcIhadLJnHQsga7VDWE
eyJ0ZXN0IjoxfQ.C48CnQ.O9K1VLYhxcIhadLJnHQsga7VDWE
eyJ0ZXN0IjoxfQ.C48Cng.8FhIko9bMt7898nRdve6qhSAuOI
eyJ0ZXN0IjoxfQ.C48Cng.8FhIko9bMt7898nRdve6qhSAuOI
eyJ0ZXN0IjoxfQ.C48Cnw.m-GRF4GyGn1-h5CJudKkSAxKQWw
```

Should it use timestamps with at least millisecond resolution?

It might not be much of an issue when used in real-world scenarios like creating reset password tokens and the like but it definitely is a drawback in test environments, if you want to check whether a newly created token does actually differ. 

Also you never want to introduce additional sleeping time.

Since e.g. [flask-security](https://github.com/mattupstate/flask-security)/[flask-security-fork](https://github.com/inveniosoftware/flask-security-fork) is using this lib, this might affect quite some use cases and production apps.

**Comment by ThiefMaster** [comment]
The point of the timestamp is to have the token expire after a certain duration (that's certainly not in the milliseconds in any real case) - not to make it unique. So I don't think there are any drawbacks from using only second precision.

**Comment by untitaker** [comment]
For real cases not, but for tests probably as pointed out in OP. For now you can probably use freezegun to work around this.

**Comment by paulgoetze** [comment]
@untitaker right, using freeezegun might be a nicer option anyway. Thanks for the hint, will give it a try.
