### ISSUE TITLE
JWT Concerns

### ISSUE THREAD

**Issue by kousu** [pallets/itsdangerous#79]
This security firm thinks that JWT and friends are. I wonder if you are aware of the issues they raise, and how you mitigate them in itsdangerous?

https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid

**Comment by untitaker** [comment]
This library uses JWS, with HMAC-SHA1 as fixed signing algorithm. It uses a very specific subset of the standard, so most of the post doesn't apply.
