### ISSUE TITLE
How to return false rather than error message?

### ISSUE THREAD

**Issue by ecod** [pallets/itsdangerous#81]
Hi ,I use the 0.24.

I use the URLSafeTimedSerializer, and loads with max_age. 

When the signature was expired, I want to get the return value **False** rather than the error message, how I do?

`itsdangerous.SignatureExpired: Signature age 1897 > 360 seconds`

I have read the doc, but I haven't found the solution yet.

Thank you very much.

**Comment by ThiefMaster** [comment]
`loads()` returning false or none to indicate an error makes no sense - after all, those would perfectly valid payloads. So the only option is raising an exception.

But you can easily write your own function to handle this - catch the exception and then return False.
