### ISSUE TITLE
TimedJSONWebSignatureSerializer not referenced in docs.

### ISSUE THREAD

**Issue by smitchell556** [pallets/itsdangerous#83]
I noticed that the `TimedJSONWebSignatureSerializer` isn't in the API docs on the [docs page](https://pythonhosted.org/itsdangerous/), but it is present in `index.rst`. I assume the docs just need to be rebuilt by the host? There's no reference to that class in the docs otherwise.

**Comment by davidism** [comment]
This will be handled in the next release.
