### ISSUE TITLE
Change the hash algorithm to something more secure

### ISSUE THREAD

**Issue by amirouche** [pallets/itsdangerous#88]
[Django doesn't use hashlib](https://docs.djangoproject.com/en/dev/topics/auth/passwords/#how-django-stores-passwords) they use PBKDF2 by default but somewhat recommend [argon2](https://docs.djangoproject.com/en/dev/topics/auth/passwords/#using-argon2-with-django).

I think the following article summarize the state of the art: https://hynek.me/articles/storing-passwords/

[pyca's cryptography doesn't support argon2 yet](https://github.com/pyca/cryptography/issues/2643) but it does support PBKDF2.

WDYT?

**Comment by ThiefMaster** [comment]
itsdangerous is not about password hashing, so these links are not very useful.

**Comment by amirouche** [comment]
You are right!
