### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by hugovk** [pallets/itsdangerous#92]
The last [PyPI release](https://pypi.python.org/pypi/itsdangerous) was [0.24](https://github.com/pallets/itsdangerous/releases/tag/0.24) released on 2014-03-28.

How about a new release? There's been quite a few changes since: https://github.com/pallets/itsdangerous/compare/0.24...master

**Comment by davidism** [comment]
Please don't make "make a new release" issues.

**Comment by mattparrilla** [comment]
@davidism anything I can do help to cut a new release?

Is this project dead and I should just monkeypatch? I'm currently blocked by #46 which has been resolved but PyPI hasn't been updated in a long time, as @hugovk pointed out.

**Comment by davidism** [comment]
This is a core dependency of Flask, so no, it's not dead.

You can install master with pip:

    pip install https://github.com/pallets/itsdangerous/archive/master.zip

We're currently focused on Flask, but I'll try to devote some time to making an itsdangerous release soon.
