### ISSUE TITLE
Drop support for EOL Python 2.6

### ISSUE THREAD

**Issue by hugovk** [pallets/itsdangerous#93]
A year ago it was proposed to drop Python 2.6: https://github.com/pallets/itsdangerous/pull/72.

What are the current thoughts on the matter?

Here's the pip installs for itsdangerous from PyPI for the last month from `pypinfo --percent --pip itsdangerous pyversion`:

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 2.7            |   49.9% |        831,216 |
| 3.5            |   22.4% |        373,065 |
| 3.6            |   21.5% |        357,556 |
| 3.4            |    5.5% |         91,894 |
| 2.6            |    0.4% |          7,084 |
| 3.3            |    0.2% |          2,886 |
| 3.7            |    0.1% |          1,932 |
| 3.2            |    0.0% |             82 |
| None           |    0.0% |             13 |

One of the comments from https://github.com/pallets/itsdangerous/pull/72#issuecomment-257302765:

> I'm leaning more towards removing support tbh, though there should be a reasonably long deprecation phase (previously announced) instead of a spontaneous reaction to the anniversary of its death.

If this is the way to go, what sort of deprecation phase would be suitable? How about a warning during installation on 2.6?

**Comment by davidism** [comment]
https://github.com/pallets/flask/pull/2486#issuecomment-335030941
